language: go

go:
  - 1.9.x
  - master

before_install:
  - go get -v github.com/Masterminds/glide 
  - make get-deps
  - go get -v github.com/tcnksm/ghr
  - go get -v github.com/mitchellh/gox

install:
  - gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./...

after_success:
  -  ghr -u ${GITHUB_USERNAME} -t ${GITHUB_TOKEN} -replace -prerelease --debug pre-release dist/